from models.endpoint import Endpoint
from psycopg.types.json import Jsonb


class EndpointRepository:
    #the repository now uses PostgreSQL instead of an in-memory list
    def __init__(self, connection_factory):
        self.connection_factory = connection_factory


    def create_endpoint(self, endpoint: Endpoint):  #method for creating and storing a new Endpoint
        query = """
            INSERT INTO endpoints (
                project_id,
                name,
                method,
                url,
                description,
                params,
                headers,
                body
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id, created_at, updated_at
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the INSERT query
            with conn.cursor() as cursor:
                cursor.execute(
                    query,
                    (
                        endpoint.project_id,
                        endpoint.name,
                        endpoint.method,
                        endpoint.url,
                        endpoint.description,
                        Jsonb(endpoint.params),
                        Jsonb(endpoint.headers),
                        Jsonb(endpoint.body) if endpoint.body is not None else None
                    )
                )

                #retrieve the ID and timestamps generated by PostgreSQL
                row = cursor.fetchone()

        #PostgreSQL generates the ID and timestamps for us
        endpoint.id = row[0]
        endpoint.created_at = row[1]
        endpoint.updated_at = row[2]

        return endpoint


    def get_endpoints(self) -> list[Endpoint]:  #method for returning all existing endpoints
        query = """
            SELECT
                id,
                project_id,
                name,
                method,
                url,
                description,
                params,
                headers,
                body,
                created_at,
                updated_at
            FROM endpoints
            ORDER BY id
        """

        #store Endpoint models reconstructed from database rows
        endpoints = []

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the SELECT query
            with conn.cursor() as cursor:
                cursor.execute(query)

                #retrieve all endpoint rows
                rows = cursor.fetchall()

        #convert each database row into an Endpoint model
        for row in rows:
            endpoints.append(
                Endpoint(
                    id=row[0],
                    project_id=row[1],
                    name=row[2],
                    method=row[3],
                    url=row[4],
                    description=row[5],
                    params=row[6],
                    headers=row[7],
                    body=row[8],
                    created_at=row[9],
                    updated_at=row[10]
                )
            )

        return endpoints


    def get_endpoint_by_id(self, endpoint_id: int) -> Endpoint | None:  #method for returning a single endpoint
        query = """
            SELECT
                id,
                project_id,
                name,
                method,
                url,
                description,
                params,
                headers,
                body,
                created_at,
                updated_at
            FROM endpoints
            WHERE id = %s
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the SELECT query
            with conn.cursor() as cursor:
                cursor.execute(query, (endpoint_id,))

                #retrieve the matching endpoint, if one exists
                row = cursor.fetchone()

        #no row means no endpoint with this ID exists
        if row is None:
            return None

        #convert the database row back into our Endpoint model
        return Endpoint(
            id=row[0],
            project_id=row[1],
            name=row[2],
            method=row[3],
            url=row[4],
            description=row[5],
            params=row[6],
            headers=row[7],
            body=row[8],
            created_at=row[9],
            updated_at=row[10]
        )


    def get_endpoints_by_project(self, project_id: int) -> list[Endpoint]:  #method for returning endpoints belonging to a project
        query = """
            SELECT
                id,
                project_id,
                name,
                method,
                url,
                description,
                params,
                headers,
                body,
                created_at,
                updated_at
            FROM endpoints
            WHERE project_id = %s
            ORDER BY id
        """

        #store only the endpoints belonging to the requested project
        endpoints = []

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the SELECT query
            with conn.cursor() as cursor:
                cursor.execute(query, (project_id,))

                #retrieve all matching endpoint rows
                rows = cursor.fetchall()

        #convert each database row into an Endpoint model
        for row in rows:
            endpoints.append(
                Endpoint(
                    id=row[0],
                    project_id=row[1],
                    name=row[2],
                    method=row[3],
                    url=row[4],
                    description=row[5],
                    params=row[6],
                    headers=row[7],
                    body=row[8],
                    created_at=row[9],
                    updated_at=row[10]
                )
            )

        return endpoints


    def update_endpoint(self, endpoint_id: int, endpoint: Endpoint):  #method for updating an endpoint
        query = """
            UPDATE endpoints
            SET
                name = %s,
                method = %s,
                url = %s,
                description = %s,
                params = %s,
                headers = %s,
                body = %s,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = %s
            RETURNING
                id,
                project_id,
                name,
                method,
                url,
                description,
                params,
                headers,
                body,
                created_at,
                updated_at
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the UPDATE query
            with conn.cursor() as cursor:
                cursor.execute(
                    query,
                    (
                        endpoint.name,
                        endpoint.method,
                        endpoint.url,
                        endpoint.description,
                        Jsonb(endpoint.params),
                        Jsonb(endpoint.headers),
                        Jsonb(endpoint.body) if endpoint.body is not None else None,
                        endpoint_id
                    )
                )

                #retrieve the updated endpoint returned by PostgreSQL
                row = cursor.fetchone()

        #no row means no endpoint with this ID exists
        if row is None:
            return None

        #convert the updated database row back into an Endpoint model
        return Endpoint(
            id=row[0],
            project_id=row[1],
            name=row[2],
            method=row[3],
            url=row[4],
            description=row[5],
            params=row[6],
            headers=row[7],
            body=row[8],
            created_at=row[9],
            updated_at=row[10]
        )


    def delete_endpoint(self, endpoint_id: int):  #method for deleting an endpoint
        query = """
            DELETE FROM endpoints
            WHERE id = %s
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #delete the endpoint with the requested ID
            with conn.cursor() as cursor:
                cursor.execute(query, (endpoint_id,))

        return None