from models.project import Project

class ProjectRepository:
    #the repository now uses PostgreSQL instead of an in-memory list
    def __init__(self, connection_factory):
        self.connection_factory = connection_factory

    def create_project(self, project: Project):
        query = """
            INSERT INTO projects (name, description)
            VALUES (%s, %s)
            RETURNING id, created_at, updated_at
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute SQL and retrieve results
            with conn.cursor() as cursor:
                cursor.execute(
                    query,
                    (project.name, project.description)
                )

                #retrieve the ID and timestamps generated by PostgreSQL
                row = cursor.fetchone()

        #PostgreSQL generates the ID and timestamps for us
        project.id = row[0]
        project.created_at = row[1]
        project.updated_at = row[2]

        return project

    def get_project_by_id(self, project_id: int) -> Project | None:
        query = """
            SELECT id, name, description, created_at, updated_at
            FROM projects
            WHERE id = %s
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the SELECT query
            with conn.cursor() as cursor:
                cursor.execute(query, (project_id,))

                #retrieve the matching project, if one exists
                row = cursor.fetchone()

        #no row means no project with this ID exists
        if row is None:
            return None

        #convert the database row back into our Project model
        return Project(
            id=row[0],
            name=row[1],
            description=row[2],
            created_at=row[3],
            updated_at=row[4]
        )

    def get_projects(self) -> list[Project]:
        query = """
            SELECT id, name, description, created_at, updated_at
            FROM projects
            ORDER BY id
        """

        #store the Project models reconstructed from database rows
        projects = []

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the SELECT query
            with conn.cursor() as cursor:
                cursor.execute(query)

                #retrieve all matching project rows
                rows = cursor.fetchall()

        #convert each database row into a Project model
        for row in rows:
            projects.append(
                Project(
                    id=row[0],
                    name=row[1],
                    description=row[2],
                    created_at=row[3],
                    updated_at=row[4]
                )
            )

        return projects

    def update_project(self, project_id: int, project: Project):
        query = """
            UPDATE projects
            SET name = %s,
                description = %s,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = %s
            RETURNING id, name, description, created_at, updated_at
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #create a cursor to execute the UPDATE query
            with conn.cursor() as cursor:
                cursor.execute(
                    query,
                    (project.name, project.description, project_id)
                )

                #retrieve the updated project returned by PostgreSQL
                row = cursor.fetchone()

        #no row means no project with this ID exists
        if row is None:
            return None

        #convert the updated database row back into a Project model
        return Project(
            id=row[0],
            name=row[1],
            description=row[2],
            created_at=row[3],
            updated_at=row[4]
        )

    def delete_project(self, project_id: int):
        query = """
            DELETE FROM projects
            WHERE id = %s
        """

        #open a database connection for this repository operation
        with self.connection_factory() as conn:
            #delete the project with the requested ID.
            with conn.cursor() as cursor:
                cursor.execute(query, (project_id,))

        #endpoint deletion is handled automatically by PostgreSQL's
        #ON DELETE CASCADE foreign-key constraint.
        return None